<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ATMECSINLT-002" name="com.yatra.testscript.ValidateUserDetails" tests="16" failures="1" timestamp="2019-09-18T17:06:16 IST" time="69.009" errors="0">
  <testcase name="bookingInforamtion" time="24.663" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="sortedByRating" time="17.115" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="hotelSelection" time="5.979" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="switchToHotelTab" time="0.074" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="selectRooms" time="10.102" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="userInformation" time="3.787" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="paymentPageInformation" time="7.276" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateName" time="0.005" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateCostAtUPI" time="0.000" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateCostAtpaymentpage" time="0.001" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validatePlace" time="0.001" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateRating" time="0.002" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateSortByRatings" time="0.001" classname="com.yatra.testscript.ValidateUserDetails">
    <failure type="java.lang.AssertionError" message="Sorted by star Rating not met actualHotelRatings is: [4.5, 4, 3.5, 4, 4, 4, 4, 4.5, 4, 4, 4, 3.5, 4, 5, 3.5, 4, 4.5, 4.5, 4, 4.5, 3.5, 2.5, 4.5, 4, 4, 4.5, 4, 3.5, 4.5, 3.5] expectedHotelRatings is: [5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 2.5]: Lists differ at element [0]: 5 != 4.5 expected [5] but found [4.5]">
      <![CDATA[java.lang.AssertionError: Sorted by star Rating not met actualHotelRatings is: [4.5, 4, 3.5, 4, 4, 4, 4, 4.5, 4, 4, 4, 3.5, 4, 5, 3.5, 4, 4.5, 4.5, 4, 4.5, 3.5, 2.5, 4.5, 4, 4, 4.5, 4, 3.5, 4.5, 3.5] expectedHotelRatings is: [5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 2.5]: Lists differ at element [0]: 5 != 4.5 expected [5] but found [4.5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:1033)
at com.yatra.utility.Validation.validateRating(Validation.java:112)
at com.yatra.base.ValidationScript.validateHotelRatings(ValidationScript.java:69)
at com.yatra.testscript.ValidateUserDetails.validateSortByRatings(ValidateUserDetails.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- validateSortByRatings -->
  <testcase name="validateCheckIn" time="0.001" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateTotalRooms" time="0.001" classname="com.yatra.testscript.ValidateUserDetails"/>
  <testcase name="validateTotalMembers" time="0.001" classname="com.yatra.testscript.ValidateUserDetails"/>
</testsuite> <!-- com.yatra.testscript.ValidateUserDetails -->
